---
- hosts: new
  gather_facts: no
  connection: local

  tasks:
  - name: DEFINE PROVIDER
    set_fact:
     provider:
       host: "{{ ansible_host }}"
       username: "{{ username }}"
       password: "{{ password }}"
       auth_pass: "{{ auth_pass }}"


  - name: SHOW RUN | BEG BANNER
    ios_command:
      provider: "{{ provider }}"
      authorize: yes
      commands:
        - show run | beg banner
    register: banner
  - debug: var=banner.stdout_lines
