---
- hosts: ios
  gather_facts: no
  connection: local
#  validate_certs: False

  tasks:
  - name: DEFINE PROVIDER
    set_fact:
     provider:
       host: "{{ ansible_host }}"
       username: "{{ username }}"
       password: "{{ password }}"
       auth_pass: "{{ auth_pass }}
       
  - name: Reading catalyst...
    ios_command:
      provider: "{{ provider }}"
      authorize: yes
      commands:
       - show run interface {{ iface }}
    register: out 
  - name: Output
    debug: var=out.stdout_lines
